export const DEFAULT_PAGE_SIZE = 10;
export const INITIAL_PAGE_NUMBER = 1;

export const SAMPLE_CONTACTS = [
  {
    id: 1,
    email: "brealy0@who.int",
    name: "Brennen Realy",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 2,
    email: "mjaime1@jigsy.com",
    name: "Manny Jaime",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 3,
    email: "whuddlestone2@mapquest.com",
    name: "Wilton Huddlestone",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 4,
    email: "ctapply3@newsvine.com",
    name: "Crin Tapply",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 5,
    email: "ashallow4@reference.com",
    name: "Antons Shallow",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 6,
    email: "jpeever5@mysql.com",
    name: "Junette Peever",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 7,
    email: "jpalmby6@webs.com",
    name: "Julee Palmby",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 8,
    email: "itowe7@toplist.cz",
    name: "Izak Towe",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 9,
    email: "bgosselin8@cornell.edu",
    name: "Blondy Gosselin",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 10,
    email: "jbrushneen9@fotki.com",
    name: "Joceline Brushneen",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 11,
    email: "wmarskella@mayoclinic.com",
    name: "William Marskell",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 12,
    email: "ppaysb@salon.com",
    name: "Petronille Pays",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 14,
    email: "kbauckhamd@gmpg.org",
    name: "Kirby Bauckham",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 15,
    email: "rmcmorrane@si.edu",
    name: "Rosella McMorran",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 16,
    email: "dlettyf@wikimedia.org",
    name: "Donaugh Letty",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 17,
    email: "lduforeg@rediff.com",
    name: "Luis Dufore",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 18,
    email: "dtantih@quantcast.com",
    name: "Delly Tanti",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 19,
    email: "meakini@163.com",
    name: "Margarete Eakin",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 20,
    email: "agillhespyj@php.net",
    name: "Agneta Gillhespy",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 21,
    email: "orasherk@behance.net",
    name: "Osbert Rasher",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 43,
    email: "binman16@ycombinator.com",
    name: "Blaine Inman",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 44,
    email: "mgeertz17@who.int",
    name: "Mychal Geertz",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 45,
    email: "ogilffillan18@squarespace.com",
    name: "Olly Gilffillan",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 46,
    email: "bsteutly19@naver.com",
    name: "Berti Steutly",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 47,
    email: "cclemson1a@google.com.hk",
    name: "Cyndy Clemson",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 48,
    email: "epennazzi1b@youku.com",
    name: "Eward Pennazzi",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 49,
    email: "gelphick1c@taobao.com",
    name: "Gerardo Elphick",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 50,
    email: "jstutard1d@chicagotribune.com",
    name: "Janice Stutard",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 51,
    email: "gblay1e@dailymail.co.uk",
    name: "Gabriella Blay",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 52,
    email: "cgunton1f@google.com",
    name: "Cherida Gunton",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 53,
    email: "mcruise1g@eepurl.com",
    name: "Michaelina Cruise",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 54,
    email: "mmorrell1h@behance.net",
    name: "Martainn Morrell",
    createdAt: "Feb 5, 2021",
  },
  {
    id: 55,
    email: "agrishunin1i@photobucket.com",
    name: "Aarika Grishunin",
    createdAt: "Feb 5, 2021",
  },
];
